GET http://localhost:8001

###

GET http://localhost:8001/dancly/cards

###

POST http://localhost:8001/dancly/cards
Content-Type: application/json

{
    "name": "Elon Musk",
    "imgUrl": "https://image.cnbcfm.com/api/v1/image/105401065-1534435276321elon.jpg"
}

###

